component:
  componentReferences: []
  name: kyma-project.io/module/example
  provider: internal
  repositoryContexts:
  - baseUrl: operator-test-registry.localhost:50241
    componentNameMapping: urlPath
    type: ociRegistry
  resources:
  - access:
      digest: sha256:bac0dfedc8b7ae961db3091f2e116091651701ab7bff8adc0eee3fa7c62fe1e4
      type: localOciBlob
    name: manifest
    relation: local
    type: yaml
    version: v0.0.10
  - access:
      digest: sha256:6ec1e4757297c2ca8b95586e8300db6a61f364886d8c2f953de33c09db50f77e
      type: localOciBlob
    name: chart
    relation: local
    type: helm-chart
    version: v0.0.10
  sources: []
  version: v0.0.10
meta:
  schemaVersion: v2

