name: 'manifest'
type: 'yaml'
relation: 'local'
input:
  type: "file"
  path: "./data/manifest.yaml" # path is relative to the current resource file
  mediaType: "application/yaml" # optional, will be defaulted to application/octet-stream
---
name: 'chart'
type: 'helm-chart'
relation: 'local'
input:
  type: 'dir'
  compress: true
  path: "./data/nginx-ingress" # path is relative to the current resource file