apiVersion: v1
kind: Config
current-context: shoot--jellyfish--ab-test1
contexts:
  - name: shoot--jellyfish--ab-test1
    context:
      cluster: shoot--jellyfish--ab-test1
      user: shoot--jellyfish--ab-test1-token
clusters:
  - name: shoot--jellyfish--ab-test1
    cluster:
      server: 'https://api.ab-test1.jellyfish.shoot.canary.k8s-hana.ondemand.com'
      certificate-authority-data: >-
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lSQU1OeTJENlNWSDMvMEFSSFpPMEVuWUF3RFFZSktvWklodmNOQVFFTEJRQXcKRFRFTE1Ba0dBMVVFQXhNQ1kyRXdIaGNOTWpJd05qSXhNRGN5TXpNeVdoY05Nekl3TmpJeE1EY3lNek15V2pBTgpNUXN3Q1FZRFZRUURFd0pqWVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBS1d3CnZwaXoyWnRyTjg2ZzQzTmZuMUpyQ2owTDBWSFR3OFY1cHZ0Rnh1d0kvdStlWWcyZHZxTFVvSHRSOTlwd1ppeUwKaE1VQzlJbVhHbFN3V3cxNGxHT3UzSVVYQVYrWlNRaFhTd2tHQlhaQm0xUURob0g2N0JNbXlaUVR2TytlVE5JaApVTS84VkI3bG5hNjRUelRxZkNGVmlBQkNYeElZcEl6ZEErYUkvMXN3SVJvWWVZaVBGVzlodkZTYWVQNVBNNzlHCkd5ZnhDWE50enVDMm9WaFI3UlB0TkFZYkpTSnlOMHovdDZmZC9CRDB5amsya2IrREk4SGJiUVprYmE4bGY5OFIKVklCUER5U1RyMjdZcU00RTlYRUdSQ0F3MVUyZE1GQ3h5bnBLeWI1S2kreGxyWDRqTnlKRDhVSDB6cWc1VFMrOQpEMnRVZDZScHpoZlhhcDlFbktrQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0dtTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZLeDJ1czR5bFMrNmp6ZVBnbC9sYUE0cmFaVTdNQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFCM1VkOHB5S1VQUnJZb3YxcEUycGM4Mzd3eWlMdnNsWkkvMFBPdnNQUGtGSmw5NjNneQpWK0VSTkpiQXkrRGduTXBEbmN4VUlNK3ZYWVdQbkw2b1V6YXJBWjd6SXRvMWdEMzA4VXJ2WDlyVWhaLzAraTl0CjhrVnJiT2VpYjR3ZFZXS0F6U1B6MUd5Rmh2VHpwcVk2NUJyS1pDL1EyLy93M2g4N2ovSTloQXJDOTFTMDBKd1gKejcwVUtmL3RGdStGbElRTEVFL0J2VmxSUHdsTGdUMGI1cWJYS1pTa0o1M3FEYmVOVVRMVnNtdzdiNVVkNFNjbgp0SjROV0hvMVI5RGYyZnU1QmxCZGlZRjZFNDltcFlXbmRTQXVvcDFrSGp6cWt4cWp1TlJ0UHYyNWkySXA2S3FDCjNFR08zNUoxTUJwNVIxL0xHUWtRa2FDbWZ6UVh3MEs4TlRCQwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
users:
  - name: shoot--jellyfish--ab-test1-token
    user:
      token: >-
        toR66RhOivpeYuasFdhpzsgMMqi8SjD19KeFIlzhMrgM0aVTmtwCAOm2w9NKsXlmxT5wm03tESA1nv2x9EfaZnKeOINkqVPTY9rlRL38ftGAq8yoxKsnPwz76NijBpSA
