kind: ConfigMap
apiVersion: v1

metadata:
  name: kyma-component-istio-rapid
  namespace: default
  labels:
    "operator.kyma-project.io/managed-by": "kyma-operator"
    "operator.kyma-project.io/controller-name": "istio"
    "operator.kyma-project.io/channel": "rapid"
data:
  istio: |-
    kind: IstioConfiguration
    group: kyma.kyma-project.io
    resource: istioconfigurations
    version: v1alpha1
    spec:
      foo: "Rapid Speed!"