apiVersion: operator.kyma-project.io/v1alpha1
kind: Kyma
metadata:
  name: kyma-sample
  namespace: default
spec:
  release: v1.0.2
  components:
    - name: istio
    - name: serverless
    - name: helm
      settings:
        chartName: cert-manager
        create: "true"
        releaseName: jet
        releaseNamespace: default
        repoName: jetstack
        url: https://charts.jetstack.io