apiVersion: operator.kyma-project.io/v1alpha1
kind: ModuleTemplate
metadata:
  name: moduletemplate-sample-manifest
  namespace: default
  labels:
    "operator.kyma-project.io/managed-by": "kyma-operator"
    "operator.kyma-project.io/controller-name": "manifest"
spec:
  channel: stable
  data:
    crd-url: ""
    kind: Manifest
    resource: manifests
    apiVersion: component.kyma-project.io/v1alpha1
    spec: 
      charts:
      - chartName: nginx-ingress
        repoName: nginx-stable
        releaseName: nginx
        url: https://helm.nginx.com/stable
        clientConfig: "CreateNamespace=true,Namespace=nginx"
