apiVersion: operator.kyma-project.io/v1alpha1
kind: Kyma
metadata:
  name: kyma-sample
  namespace: default
spec:
  channel: stable
  components:
    - name: istio
    - name: serverless
    - name: manifest