apiVersion: operator.kyma-project.io/v1alpha1
kind: Kyma
metadata:
  name: kyma-sample
  namespace: operator-system
spec:
  release: v2.2.3
  components:
    - name: test
      settings:
        key: value
