apiVersion: operator.kyma-project.io/v1alpha1
kind: Kyma
metadata:
  name: kyma-sample
  namespace: operator-system
spec:
  revisionHistoryLimit: 4
  release: v2.1.2
  components:
    - name: test
      settings:
        key: value2
