linters:
  enable-all: true
  disable:
    - exhaustivestruct
    - golint
    - interfacer
    - maligned
    - scopelint
    - forcetypeassert
  linters-settings:
    gci:
      local-prefixes: github.com/kyma-project