linters:
  enable-all: true
  disable:
    - exhaustivestruct
    - golint
    - interfacer
    - maligned
    - scopelint
    - forcetypeassert
    - godox
    - wsl
    - nlreturn
    - bodyclose
    - contextcheck
    - nilerr
    - noctx
    - rowserrcheck
    - sqlclosecheck
    - structcheck
    - tparallel
    - unparam
    - wastedassign
    - exhaustruct
  linters-settings:
    gci:
      local-prefixes: github.com/kyma-project