name: "Check API Version Compatibility"

on:
  pull_request:
    branches: [ "api-changes-pipeline-test" ]
    types:
      - "opened"
      - "reopened"
      - "synchronize"
      - "labeled"
      - "unlabeled"

jobs:
  check-api-diff:
    name: Diff APIs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR ref of lifecycle-manager
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y dyff

      - name: Compare CRD Versions
        run: |
          set -e
          CONFIG_FILE=api-version-compatibility-config.yaml
          CRD_PATH=./config/crd/bases
          
          for file in $CRD_PATH/*.yaml; do
            versions=$(yq e '.spec.versions[].name' "$file")
            versions=($versions)
            for ((i=0; i<${#versions[@]}-1; i++)); do
              v1=${versions[i]}
              v2=${versions[i+1]}
          
              exclusions_v1=$(yq e ".\"$(basename $file)\".exclusions.$v1[]" $CONFIG_FILE)
              exclusions_v2=$(yq e ".\"$(basename $file)\".exclusions.$v2[]" $CONFIG_FILE)
              
              yq e ".spec.versions.[] | select(.name == \"$v1\") | .schema.openAPIV3Schema.properties" "$file" > 1.yaml
              for exclusion in $exclusions_v1; do
                yq e "del($exclusion)" -i 1.yaml
              done
              
              yq e ".spec.versions.[] | select(.name == \"$v2\") | .schema.openAPIV3Schema.properties" "$file" > 2.yaml
              for exclusion in $exclusions_v2; do
                yq e "del($exclusion)" -i 2.yaml
              done
              
              if ! dyff between 1.yaml 2.yaml --exclude-regexp ".*description" --set-exit-code; then
                echo "Difference found between versions $v1 and $v2 in $file"
                echo "To add an exclusion, update $CONFIG_FILE with the necessary exclusions."
                exit 1
              fi
              done
          done

      - name: Cleanup
        run: |
          rm -f 1.yaml 2.yaml