name: "Check for changes in Controller APIs"

on:
  pull_request:
    branches: [ "api-changes-pipeline-test" ]
    types:
      - "opened"
      - "reopened"
      - "synchronize"
      - "labeled"
      - "unlabeled"

jobs:
  check-api-diff:
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'confirm/api-changes') }}
    name: Check API diff
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR ref of lifecycle-manager
        uses: actions/checkout@v4

      - name: Copy PR CRDs to temp dir
        run: mkdir -p /tmp/pr-crds && cp ./config/crd/bases/* /tmp/pr-crds/

      - name: Checkout main of lifecycle-manager
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Copy main CRDs to temp dir
        run: mkdir -p /tmp/main-crds && cp ./config/crd/bases/* /tmp/main-crds/

      - name: Compare CRD files
        run: |
          pr_files=$(ls /tmp/pr-crds)
          main_files=$(ls /tmp/main-crds)
          if [[ "$pr_files" != "$main_files" ]]; then
            for file in $pr_files; do
              if [[ ! " $main_files " =~ " $file " ]]; then
                echo "File $file is present in PR but not in main."
                exit 1
              fi
            done
  
            for file in $main_files; do
              if [[ ! " $pr_files " =~ " $file " ]]; then
                echo "File $file is present in main but not in PR."
                exit 1
              fi
            done